### ISSUE TITLE
How to add stack but not save when back?

### ISSUE THREAD

**Issue by saifudin** [smart-fun/TabStacker#4]
Sorry, what is the correct way or idea to add new stack but not save when go back,
Stack 1 -- stack 2 -- stack 3  -- stack 4 . i must not save stack 3.  so i go to stack 2 from stack 4. but when i back from stack 2 i go to stack 1.   Thanks.
#sorry my bad English.  :)

**Comment by smart-fun** [comment]
Hello,

there is no direct way to do this at the moment. What I suggest you to do, when you you go from fragment3 to fragment4, is to call:

`mTabStacker.onBackPressed();`
`mTabStacker.replaceFragment(fragment4, animation);`

this way fragment3 is removed from the stack and the screen, and fragment4 is displayed instead. If you click on back, then it goes directly from fragment4 to fragment2.

The only problem with this solution is animations. If you have animations you will see fragment3 moving out of the screen.

I can think of adding a new feature to the library to remove a fragment in the middle of a stack, but I already see some potential issues with transparent fragments.

Tell me if the proposed solution solves your problem,

thanks,

Arnaud.

**Comment by saifudin** [comment]
Nice..
this solution solved my problem.
i use 
mTabStacker.onBackPressed();
mTabStacker.replaceFragment(fragment4, null);  and no animation problem

Thanks a Lot
